export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const USERS_SUCCESS = 'USER_SUCCESS';
export const USERS_REQUEST = 'USERS_REQUEST';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';