export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const USERS_SUCCESS = 'USER_SUCCESS';
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_FAILURE = 'USERS_FAILURE';
export const USER_SIGNUP = 'USER_SIGNUP';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORYS = 'ADD_CATEGORYS';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_FAILURE = 'CATEGORY_FAILURE';

export const ADD_COMMENT = "ADD_COMMENT";
export const COMMENT_FAILURE = "COMMENT_FAILURE";
export const COMMENT_LOADING = "COMMENT_LOADING";

export const ADD_ORDER = "ADD_ORDER";
export const ORDER_FALURE = "ORDER_FALURE";
export const DELETE_ORDER = "DELETE_ORDER";
export const ADD_ORDERDETAILS = "ADD_ORDERDETAILS";
export const ORDERDETAILS_FALURE = "ORDERDETAILS_FALURE";

export const ADD_COMPONENT_PRODUCTS = "ADD_COMPONENTS";
export const COMPONENT_PRODUCTS_LOADING = "COMPONENTS_LOADING";
export const COMPONENT_PRODUCTS_FAILURE = "COMPONENTS_FAILURE";